name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for new release'
        required: true

env:
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Run the Maven verify phase
      run: mvn $MAVEN_CLI_OPTS verify
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image for Admin UI
      uses: docker/build-push-action@v5
      with:
        context: ./admin-ui
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.event.inputs.version }}
    # - name: Make release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
    #       knowledge-directory-${{ github.events.inputs.version }}-with-dependencies.jar
    #       smart-connector-rest-dist-${{ github.events.inputs.version }}-with-dependencies.jar

    # - name: Build Docker image for Admin UI
    #   run: docker buildx build ./admin-ui --platform linux/arm64,linux/amd64 --tag ghcr.io/sophietje/knowledge-engine/${{ github.event.inputs.version }} --push
    #   # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
