name: Make draft release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version for new release (X.Y.Z)"
        required: true
        type: string

env:
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.7-eclipse-temurin-17-alpine

    steps:
    - run: sudo apt install -y git
    - uses: actions/checkout@v4
    - name: Build JARs
      run: mvn $MAVEN_CLI_OPTS package
    - name: Create tag
      run: |
        git tag -a ${{ inputs.version }} -m ${{ inputs.version }}
        git push origin ${{ inputs.version }}
    - name: Draft release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          smart-connector-rest-dist-${{ inputs.version }}-with-dependencies.jar
          knowledge-directory-${{ inputs.version }}-with-dependencies.jar
        tag_name: ${{ inputs.version }}
        draft: true
        generate_release_notes: true
        make_latest: true
